_select_data:
  aspect-ratios:
    - square
    - portrait
    - portrait-tall
    - landscape
    - landscape-wide

  column-widths:
    col-6: One Half
    col-12: Full Width
    col-4: One Third
    col-3: One Quarter
    col-6_sm-12: One Half (Stacked on Mob)
    col-4_sm-12: One Third (Stacked on Mob)
    col-3_sm-12: One Quarter (Stacked on Mob)