design:
  dark-text_color: '#413c3c'
  medium-text_color: '#4b3c3c'
  light-text_color: '#f8f6f4'
  featured-text_color: '#f59186'
  featured-text-darker_color: '#e37165'
  light_color: '#efdcd9'
  v-light_color: '#f8f6f4'
  featured_color: '#f59186'